[build]
  publish = "2025_site"  # Publica directamente el contenido de 2025_site

[[redirects]]
  from = "/"
  to = "/"
  status = 200

[[redirects]]
  from = "/2024"
  to = "/2024/"
  status = 301

[[redirects]]
  from = "/2024/*"
  to = "/2024/index.html"
  status = 200
  force = true
