[build]
  publish = "."  # desde la raíz, tienes carpetas 2024 y 2025_site

# Redirige raíz a /2025 para que la URL muestre /2025 (redirección permanente)
[[redirects]]
  from = "/"
  to = "/2025/"
  status = 301

# Redirige /2025 sin barra a /2025/ con barra para evitar problemas de rutas relativas
[[redirects]]
  from = "/2025"
  to = "/2025/"
  status = 301

# Rewrite para servir archivos de 2025_site cuando se accede a /2025/
[[redirects]]
  from = "/2025/*"
  to = "/2025_site/:splat"
  status = 200

# Permite que /2024/* sirva la carpeta 2024 y sus subrutas
[[redirects]]
  from = "/2024/*"
  to = "/2024/:splat"
  status = 200
