[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/2024/"
  status = 301

[[redirects]]
  from = "/2024"
  to = "/2024/"
  status = 301

[[redirects]]
  from = "/2025"
  to = "/2025/"
  status = 301

# Rutas para SPA (para que las rutas internas funcionen)
[[redirects]]
  from = "/2024/*"
  to = "/2024/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/2025/*"
  to = "/2025/index.html"
  status = 200
  force = true
