[build]
  publish = "."

[[redirects]]
from = "/"
to = "/2024/"
status = 301

[[redirects]]
from = "/2024"
to = "/2024/"
status = 301

[[redirects]]
from = "/2025/*"
to = "/2025/index.html"
status = 200
