[build]
  publish = "."

# Muestra directamente el index del sitio página raíz
[[redirects]]
from = "/"
to = "/2025_site/index.html"
status = 200

# Redirige /2025 a raíz si alguien lo pone manualmente
[[redirects]]
from = "/2025"
to = "/2025_site/index.html"
status = 200

# 2024
[[redirects]]
from = "/2024"
to = "/2024/index.html"
status = 200
