[build]
  publish = "."  # Publica desde raíz para acceder a 2024 y 2025 carpetas

# Redirige raíz a /2025 (cambia URL en navegador)
[[redirects]]
  from = "/"
  to = "/2025"
  status = 301

# Redirige /2025 sin slash a /2025/ con slash para rutas relativas
[[redirects]]
  from = "/2025"
  to = "/2025/"
  status = 301

# 2025 sirve contenido desde carpeta /2025/ (Reflex export renombrada)
# No necesitas redirect ni rewrite aquí si la carpeta se llama 2025

# Permite que /2024/* sirva contenido estático con subrutas
[[redirects]]
  from = "/2024/*"
  to = "/2024/:splat"
  status = 200
