[build]
  publish = "public

#[[redirects]]
#from = "/2025/*"
#to = "/2025/index.html"
#status = 200

#redireccion a 2025
#[[redirects]]
#  from = "/2025_dev/*"
#  to = "/2025_dev/public/index.html"
#  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
